name:                not-a-trace
version:             0.1.0.0
github:              "snut/not-a-trace"
license:             BSD3
author:              "snut"
maintainer:          "example@example.com"
copyright:           "2021 Daniel Watts"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/snut/not-a-trace#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- JuicyPixels
- linear
- time
- random
- vector
- vector-strategies
- mtl

library:
  source-dirs: src

executables:
  not-a-trace:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -funbox-strict-fields
    dependencies:
    - not-a-trace

tests:
  not-a-trace-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - not-a-trace
